name = "Scadrial"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a619ee7e2014342e89ef022379364435961a42e72d9dfafec1bf87422b12cf7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
