name = "Scadrial"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f90248f2b446cc637e8290ece7b02f1b6677d084b8b2fe6ef22f615418890ca2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
