name = "Scadrial"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "055e9a5a94cd3076c6445ded904d7161016f84334b31b2e9d07dceaf1e95f0f2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
