name = "kTiliNakor"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "214d6dda7ef3f07acd7d75d03715da2654e85624afba4b49955d406cfb95cf99"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
