name = "kTiliNakor"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3676b3c16085674c0a4046a1ebda3debeb7397c573254841ff7c999ed35473e8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
