name = "TiliNakor"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f262e02cebc28a91eb626b096450839b8c12a880fc318408f56dd51a5a872021"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
