name = "TiliNakor"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db6fed6801819cc1415df6d6c0d859eac372f6afdf5598a629b2bdacfda107be"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
