name = "TiliNakor"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3007d61c00236570331c212c84fd67a6363f9f1062ddb897a3f5786b78f389e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
