name = "Roshar"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "848afd5c92ee2e6dc178b72962edb352057a77dd5bbd7e4dd77f61dbbc02db0d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
