name = "TiliNakor_test"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d99417a6f10a4261568e32ceaeaa3943e7b86bc7dc9958331b4b79fe2fb25eef"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
