name = "TiliNakor_test"
author = "Nakorek"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e3d1bdd0cf5bad6addcd0404de632d922421b7a29d1f196209e70b7022757b5"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
